### ISSUE TITLE
Использование домена вместо ip

### ISSUE THREAD

**Issue by vanyaindigo** [hookzof/fast_mtproxy#3]
Привет, подскажи, можно ли при создании сервера использовать Clouflare-fronting domain?

**Comment by hookzof** [comment]
Поподробнее если можно. Речь идёт про использование домена (через Cloudflare) в качестве домена для сервера (флаг -D)?

**Comment by vanyaindigo** [comment]
Нет, при создании строки, tg автоматически подставляется ip-адрес сервера. Как вместо ip подключаться по доменному имени?

**Comment by hookzof** [comment]
Да, через cloudflare можно сделать. Сначала домен туда перенести, потом добавить запись (вкладка DNS) (как на скриншоте)
![A4F42716-72F5-47A8-AB09-73D8DA542134](https://user-images.githubusercontent.com/22233835/69160684-0bd81100-0afb-11ea-820d-9b7c32c39c86.jpeg)

myproxy.domain.ru будет, вместо 1.1.1.1

**Comment by vanyaindigo** [comment]
Вот только Cloudflare проксирует только WebSocket. Есть ли его поддержка в MTProxy?

**Comment by hookzof** [comment]
Поддержки нет, проксирование отключается в последнем пункте, если оно не нужно.

**Comment by vanyaindigo** [comment]
А вот хотелось бы именно с ним. А eSNI еще не завезли?

**Comment by hookzof** [comment]
eSNI тоже пока нет, но думаю поддержка уже не за горами.

**Comment by vanyaindigo** [comment]
Вопрос такой кстати уже подымали https://github.com/TelegramMessenger/MTProxy/issues/352

**Comment by vanyaindigo** [comment]
Я кстати увидел, что протокол, под который мимикрирует MTProxy - не TLS1.3, a TLS1.2

**Comment by hookzof** [comment]
Официальная под 1.3, это можно увидеть через Wireshark

**Comment by vanyaindigo** [comment]
Так я и смотрю в Wireshark и вижу 1.2

**Comment by hookzof** [comment]
При загрузке большого файла через прокси TLS 1.3, где там 1.2 я не увидел.
![wireshark](https://user-images.githubusercontent.com/22233835/69665955-74dffb80-109c-11ea-8147-9b60886e5942.png)
