### ISSUE TITLE
Add QR code 

### ISSUE THREAD

**Issue by pliashkou** [hookzof/fast_mtproxy#4]
Hey, it would be good to have some kind of QR code, which can be scanned, at the end.

Like this one https://github.com/mdp/qrterminal (or other)

Thanks for your work!

**Comment by hookzof** [comment]
Sorry for the long wait on this issue. As of now, it has been implemented - https://github.com/hookzof/fast_mtproxy/commit/50864f172ee10fd67419a2c5efd3d55dfc4835d0

Functionality is guaranteed on these platforms:
* Ubuntu 18.04/20.04
* Debian 9/10
* CentOS 7/8
